title: Rigerta Demiri
email: demiri.rigerta@gmail.com
description: >- # this means to ignore newlines until "baseurl:"

#baseurl: "https://github.com/rigerta/rigerta.github.io/" # the subpath of your site, e.g. /blog
baseurl: ""

# Build settings
remote-theme: Hyde

